name: Build iOS MAUI

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Build Unsigned App
      run: |
        dotnet publish -f net8.0-ios -c Release -p:RuntimeIdentifier=ios-arm64 -p:CodesignKey="" -p:CodesignProvision=""
        
    - name: Package to IPA
      run: |
        mkdir Payload
        # Membungkus hasil build menjadi file .ipa
        cp -r iPhoneMicClient/bin/Release/net8.0-ios/ios-arm64/iPhoneMicClient.app Payload/
        zip -r iPhoneMicClient.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mic-App-iPhone15
        path: iPhoneMicClient.ipa
